source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'
workspace 'AutoKeyboardScrollView'

xcodeproj 'InterfaceBuilderExample/InterfaceBuilderExample.xcodeproj'
xcodeproj 'ProgrammaticExample/ProgrammaticExample.xcodeproj'

pod 'AutoKeyboardScrollView', :path => '../'
