platform :ios, '8.0'

target 'InterfaceBuilderExample' do
    workspace 'AutoKeyboardScrollView'
    project 'InterfaceBuilderExample/InterfaceBuilderExample'

    use_frameworks!
    pod 'AutoKeyboardScrollView', :path => '../'
end

target 'ProgrammaticExample' do
    workspace 'AutoKeyboardScrollView'
    project 'ProgrammaticExample/ProgrammaticExample'

    use_frameworks!
    pod 'AutoKeyboardScrollView', :path => '../'
end
